import Airpods2 from "../assets/Airpods2.png";
import Macbook from "../assets/Mackbook air.png";
import Samsungs23 from "../assets/Samsung s23.png";
import PS5 from "../assets/PS5.png";
import Boatheadphone from "../assets/Boat headphone.png";
import Appleheadphone from "../assets/Apple headphone.png";
import VRHeadset from "../assets/VRHeadset.png";
import Keybord from "../assets/Keybord.png";
import iphone15promax from "../assets/Iphone15promax.png";
import h10 from "../assets/h10.png";
import h11 from "../assets/h11.png";
import w1 from "../assets/w1.png";
import e7 from "../assets/e7.png";
import v3 from "../assets/v3.png";
import w3 from "../assets/w3.png";
import e3 from "../assets/e3.png";
import laptop13 from "../assets/laptop13.png";
import laptop16 from "../assets/laptop16.png";
import w4 from "../assets/w4.png";
import k5 from "../assets/k5.png";
import w5 from "../assets/w5.png";
import h12 from "../assets/h12.png";
import k4 from "../assets/k4.png";
import laptop11 from "../assets/laptop11.png";
import k1 from "../assets/k1.png";
import w6 from "../assets/w6.png";
import fold from "../assets/fold1.png";
import laptop10 from "../assets/laptop10.png";
import k2 from "../assets/k2.png";
import h14 from "../assets/h14.png";
import iphone15 from "../assets/iphone15.png";
import Oneplus12 from "../assets/Oneplus12.png";
import laptop12 from "../assets/laptop12.png";
import e2 from "../assets/e2.png";
import w8 from "../assets/w8.png";
import e1 from "../assets/e1.png";
import BlackHeadphone from "../assets/BlackHeadphone.png";
import Realmegt from "../assets/Realmegt.png";
import v1 from "../assets/v1.png";
import pixal8 from "../assets/pixal8.png";
import w7 from "../assets/w7.png";
import w2 from "../assets/w2.png";
import p1 from "../assets/p1.png";
import p2 from "../assets/p2.png";
import controler from "../assets/controler.png";

export const productDatabase = [
  {
    id: "9",
    name: "Samsung S24 Ultra",
    image: Samsungs23,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Phone",
  },
  {
    id: "10",
    name: "Apple Headphone",
    image: Appleheadphone,
    originalPrice: 4999,
    discountedPrice: "3999",
    discount: "20% OFF",
    amount: 1,
    category: "headphone",
  },
  {
    id: "11",
    name: "PS5 Forest Edition",
    image: p1,
    originalPrice: 9999,
    discountedPrice: "5999",
    discount: "20% OFF",
    amount: 1,
    category: "PS5",
  },
  {
    id: "12",
    name: "Macbook",
    image: Macbook,
    originalPrice: 9999,
    discountedPrice: "5999",
    discount: "20% OFF",
    amount: 1,
    category: "Laptop",
  },
  {
    id: "13",
    name: "VRHeadset",
    image: VRHeadset,
    originalPrice: 9999,
    discountedPrice: "3599",
    discount: "20% OFF",
    amount: 1,
    category: "VR",
  },
  {
    id: "14",
    name: "PS5",
    image: PS5,
    originalPrice: 9999,
    discountedPrice: "1599",
    discount: "20% OFF",
    amount: 1,
    category: "PS5",
  },
  {
    id: "15",
    name: "Airpods2",
    image: Airpods2,
    originalPrice: 9999,
    discountedPrice: "999",
    discount: "20% OFF",
    amount: 1,
    category: "Earbuds",
  },
  {
    id: "16",
    name: "Keybord",
    image: Keybord,
    originalPrice: 9999,
    discountedPrice: "1299",
    discount: "20% OFF",
    amount: 1,
    category: "Keybord",
  },
  {
    id: "17",
    name: "Boatheadphone",
    image: Boatheadphone,
    originalPrice: 9999,
    discountedPrice: "899",
    discount: "20% OFF",
    amount: 1,
    category: "headphone",
  },
  {
    id: "18",
    name: "iphone 15 pro max",
    image: iphone15promax,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Phone",
  },
  {
    id: "19",
    name: "Sony Headphone",
    image: h10,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "headphone",
  },
  {
    id: "20",
    name: "Rolex Black Edition",
    image: w1,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  {
    id: "21",
    name: "Noise HeadPhone",
    image: h12,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "headphone",
  },
  {
    id: "22",
    name: "Meta VRHeadset",
    image: v3,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "VR",
  },
  {
    id: "23",
    name: "Maserati FW23",
    image: w3,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  {
    id: "24",
    name: "ASUS TUF F15",
    image: laptop16,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "laptop",
  },
  {
    id: "25",
    name: "iphone 15",
    image: iphone15,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Phone",
  },
  {
    id: "26",
    name: "PS5 Cyberpunk Edition",
    image: p2,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "PS5",
  },
  {
    id: "27",
    name: "Windows Laptop",
    image: laptop13,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Laptop",
  },
  {
    id: "28",
    name: "Rolex Diamond Edition",
    image: w4,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  {
    id: "29",
    name: "Logitech k15",
    image: k5,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Keybord",
  },
  {
    id: "30",
    name: "bo&u Headphone",
    image: h11,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "headphone",
  },
  {
    id: "31",
    name: "Rolex Green Edition",
    image: w5,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  {
    id: "32",
    name: "Pixal 8 Pro",
    image: pixal8,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Phone",
  },
  {
    id: "33",
    name: "Boat Nirvana Earbuds",
    image: e7,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Earbuds",
  },
  {
    id: "34",
    name: "Logitech Mechanical Keybord",
    image: k4,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Keybord",
  },
  {
    id: "35",
    name: "PS5 Conteroler",
    image: controler,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "PS5",
  },
  {
    id: "36",
    name: "ASUS ROG Strike",
    image: laptop11,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Laptop",
  },
  {
    id: "37",
    name: "Logitech purple Keybord",
    image: k1,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Keybord",
  },
  {
    id: "38",
    name: "Rolex Dark Edition",
    image: w6,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  {
    id: "39",
    name: "Samsung Fold 5",
    image: fold,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Phone",
  },
  {
    id: "40",
    name: "Noise Browne Headphone",
    image: h14,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "headphone",
  },
  {
    id: "41",
    name: "Lenovo Legion Laptop",
    image: laptop10,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Laptop",
  },
  {
    id: "42",
    name: "Logitech White Keybord",
    image: k2,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Keybord",
  },
  {
    id: "43",
    name: "Boat Airpods 183",
    image: e3,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Earbuds",
  },
  {
    id: "44",
    name: "Golden Rolex",
    image: w2,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  
  {
    id: "45",
    name: "Oneplus 12 Pro",
    image: Oneplus12,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Phone",
  },
  {
    id: "46",
    name: "Dell Alienware Laptop",
    image: laptop12,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Laptop",
  },
  {
    id: "47",
    name: "Mi Earbuds",
    image: e2,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Earbuds",
  },
  {
    id: "48",
    name: "Realme-GT-3",
    image: Realmegt,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Phone",
  },
  {
    id: "49",
    name: "Rolex Blue Edition",
    image: w8,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  {
    id: "50",
    name: "Realme Buds 4",
    image: e1,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "Earbuds",
  },
  {
    id: "51",
    name: "Rezer Headphone",
    image: BlackHeadphone,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "headphone",
  },
  {
    id: "52",
    name: "VR Headset",
    image: v1,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "VR",
  },
  
  {
    id: "53",
    name: "Fosills Watch",
    image: w7,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "watch",
  },
  {
    id: "54",
    name: "PS5",
    image: PS5,
    originalPrice: 9999,
    discountedPrice: "7999",
    discount: "20% OFF",
    amount: 1,
    category: "PS5",
  },
  
];
